### ISSUE TITLE
TNT_FLUSH_JOIN implementation

### ISSUE THREAD

**Issue by jobs-git** [tarantool/tarantool-c#110]
The impressive QPS achieved in [this tarantool-c application](https://gist.github.com/danikin/a5ddc6fe0cedc6257853) maybe primarily attributed to single request + multiple queries. It is evident in this part of code where we have:

```c
	for (int i = 0; i < td->tp->num_ops; ++i)
        {
                .
                .
		// Form a request to a server
		tnt_flush(tnt);
                .
                .
                //other code
	}
```

Here, tnt_flush() is working on the same memory space from that single function request.

However, in a typical server, there will be **multiple request/multiple user + fewer queries**, so to leverage the fiber processing of tarantool `tnt_flush()` should be able to work in a memory space of another request or at least work as `tnt_flush_join()` to handle the queries from other requests as well. How do we implement a C languange batch request queries involving **multiple request/multiple user + few queries**?

**Comment by bigbes** [comment]
So, ok, basically `tnt_flush` makes "send" syscall, basically writes from connector buffer to socket buffer. Probably this place for it is not fully appropriable for it, instead it should be placed in the different (second) "thread". Or I don't get your question right. What is "work in a memory space of another request"?

**Comment by jobs-git** [comment]
So, `tnt_flush` is not responsible for the actual syscall, but rather acts as a batcher, albit like: yhea query 1 go to group 1, query 2 go to the same group and so on?
