### ISSUE TITLE
Slow queries per second on multiple/concurrent independent single request.

### ISSUE THREAD

**Issue by jobs-git** [tarantool/tarantool-c#111]
In many given web applications typical scenario involves many independent request to the server's request handlers. 

In MySQL, I incorporate the connection start and connection close in the request handler. This is necessary so that the frontend and the database knows where should the data go. Closing the connection is also important so that other server requests can get a share of the connection pool.

The MySQL function structure looks like this
```c
int request_handler(){
    connect to mysql
    
    do whatever here

    close connection to mysql
}
```

In tarantool-c, I figured it would be the same. Connect to the tarantool database, do whatever then close the connection. More than this, tarantool-c is also able to group this request into one syscall so that will make it faster than MySQL power web application. However, I get the opposite. Using the tarantool-c connector, I get far fewer server request per second than MySQL connector.

My tarantool-c request handler looks like this

```c
#include <stdlib.h>
#include <stdio.h>

#include <tarantool/tarantool.h>
#include <tarantool/tnt_net.h>
#include <tarantool/tnt_opt.h>

int request_handler(){
    const char * uri = "127.0.0.1:3301";
    struct tnt_stream * tnt = tnt_net(NULL); // Allocating stream
    struct tnt_stream *tuple = tnt_object(NULL);
    tnt_set(tnt, TNT_OPT_URI, uri); // Setting URI
    //tnt_set(tnt, TNT_OPT_SEND_BUF, 0); // Disable buffering for send
    //tnt_set(tnt, TNT_OPT_RECV_BUF, 0); // Disable buffering for recv
    //tnt_connect(tnt); // Initialize stream and connect to Tarantool
    if (tnt_connect(tnt) < 0) {                      /* See note = CONNECT */
       printf("Connection refused\n");
       exit(-1);
    }
    tnt_object_add_array(tuple, 2);
    tnt_object_add_int(tuple, 2);

    tnt_object_add_int(tuple, 2);
    tnt_replace(tnt, 512, tuple);
    tnt_flush(tnt); // Send ping request
    struct tnt_reply reply;
    tnt_reply_init(&reply); // Initialize reply
    tnt->read_reply(tnt, &reply); // Read reply from server
    if (reply.code != 0) {
       printf("Insert failed %lu.\n", reply.code);
   }else{
             //printf("success!\n"); 
   }
    //tnt_reply_free(reply); // Free reply
    tnt_close(tnt); tnt_stream_free(tnt); // Close connection and free stream object
}
```

**Comment by bigbes** [comment]
Hi, @jobs-git .
1) there's no internal connection pool, so if you want to share connection - don't open/close connection every time and manage resources (like opened connections) by yourself
2) read thread/write thread pattern may be used, if you're using multiple threads in your application

**Comment by jobs-git** [comment]
I think I get it now, I moved the `connection` in the main and added a boolean that ensures it is created only once. And then only close the connection when the application server is deactivated. I got one more problem though, how do I ensure that the results of the queries goes to the rightful requestor?

**Comment by bigbes** [comment]
You should have hasmap "request_id" -> "requestor", for example
