### ISSUE TITLE
Naming confusion libtnt.so.2.0.0 vs. libtarantool.so.2.0.0

### ISSUE THREAD

**Issue by smarek** [tarantool/tarantool-c#115]
Hey, is it by purpose that `tnt/CmakeLists.txt` shows status message such as `* libtnt.so.2.0.0` (from line 83: `message(STATUS "  * lib${LIBTNT_NAME}.so.${LIBTNT_VERSION}      ")`)

But installs `./tnt/libtarantool.so.2.0.0` ? If not, I'll make a PR to fix the confusion

Thanks

**Comment by kyukhin** [comment]
I guess this is a bug.
