### ISSUE TITLE
Feature request: Request descriptor

### ISSUE THREAD

**Issue by jobs-git** [tarantool/tarantool-c#125]
`tnt->reply` seems to be an extremely blocking transaction, this results to raw MySQL being 7x faster for simple data fetch from the database. One way we can alleviate this is through an async operation, one element to implement this requires the socket connection index or socket descriptor, however, since tarantool just makes one efficient socket connection, then, the descriptor index must be from transaction request or simply request descriptor.

(if there might be other options which might solve this, that, I am not yet aware of)

see https://github.com/tarantool/tarantool/issues/3999

**Comment by Totktonada** [comment]
Are you want to work with tarantool asynchronously? If so, there is the issue #11.

**Comment by jobs-git** [comment]
This is not needed since tnt_fd() works well already, it gives the information about the notifications and so on
