### ISSUE TITLE
/usr/src/mysql_tarantool-replication/lib/tarantool-c/tnt/tnt_io.c:350:46: error: 'IOV_MAX' undeclared (first use in this function); did you mean 'INT_MAX'?

### ISSUE THREAD

**Issue by xevilstar** [tarantool/tarantool-c#128]
[ 22%] Building C object lib/tarantool-c/tnt/CMakeFiles/tnt.dir/tnt_io.c.o
cd /usr/src/mysql_tarantool-replication/lib/tarantool-c/tnt && /usr/bin/cc  -I/usr/src/mysql_tarantool-replication/lib/tarantool-c/third_party/msgpuck -I/usr/src/mysql_tarantool-replication/lib/tarantool-c/third_party -I/usr/src/mysql_tarantool-replication/lib/tarantool-c/include  -pipe -O2 -fomit-frame-pointer -ffunction-sections -fdata-sections -Wall -Wextra -std=gnu99 -D__USE_XOPEN  -pipe -O2 -fomit-frame-pointer -ffunction-sections -fdata-sections -Wall -Wextra -std=gnu99 -D__USE_XOPEN -O0 -g3 -ggdb3   -fPIC -o CMakeFiles/tnt.dir/tnt_io.c.o   -c /usr/src/mysql_tarantool-replication/lib/tarantool-c/tnt/tnt_io.c
/usr/src/mysql_tarantool-replication/lib/tarantool-c/tnt/tnt_io.c: In function 'tnt_io_sendv_raw':
/usr/src/mysql_tarantool-replication/lib/tarantool-c/tnt/tnt_io.c:350:46: error: 'IOV_MAX' undeclared (first use in this function); did you mean 'INT_MAX'?
    r = s->sbuf.txv(&s->sbuf, iov, MIN(count, IOV_MAX));

**Comment by Totktonada** [comment]
It was already fixed in PR #70 (two years ago).
