### ISSUE TITLE
tarantool-c conflicts tarantool-dev-1.5

### ISSUE THREAD

**Issue by viciious** [tarantool/tarantool-c#13]
Both packages provide /usr/lib64/libtarantool.so.* and friends and thus can not be installed on the same machine simultaneously. It'd be nice if tarantool-c provided some kind of versioning mechanism that would prevent it from conflicting with tarantool-dev-1.5. Please note that this is a feature request coming from a Mail.Ru customer/department.

**Comment by viciious** [comment]
Any progress on this?

**Comment by bigbes** [comment]
It now has soversion 2 - must fix your problem.

With best regards, Eugene.

2016-03-02 17:04 GMT+03:00 Victor Luchits <notifications@github.com>:

**Comment by bigbes** [comment]
I'll close this ticket. If it still affects you, please reopen and provide more information
