### ISSUE TITLE
Not available as deb package for Ubuntu 20.04

### ISSUE THREAD

**Issue by cyanide-burnout** [tarantool/tarantool-c#143]

**Comment by Totktonada** [comment]
tarantool-2.5 repository?

**Comment by cyanide-burnout** [comment]
deb https://download.tarantool.org/tarantool/2.4/ubuntu/ focal main
deb-src https://download.tarantool.org/tarantool/2.4/ubuntu/ focal main
deb https://download.tarantool.org/tarantool/modules/ubuntu/ focal main
deb-src https://download.tarantool.org/tarantool/modules/ubuntu/ focal main

**Comment by avtikhon** [comment]
Hi, the following repositories updated with the needed module, please check
> deb https://download.tarantool.org/tarantool/2.4/ubuntu/ focal main
> deb-src https://download.tarantool.org/tarantool/2.4/ubuntu/ focal main

**Comment by cyanide-burnout** [comment]
Solved
