### ISSUE TITLE
batch sql insert/update operations

### ISSUE THREAD

**Issue by AndreyAlifanov** [tarantool/tarantool-c#166]
It would be nice to have batch operations, like in Oracle/PostgreSQL/MSSQL.

Current syntax of insert like **insert into tbl (a,b,c) values (?,?,?), (?,?,?), (?,?,?)...** looks ugly and is very difficult to use in dynamic queries.
It would be cool if I could use arrays of parameters.
For example array of 100 integers for **a** field, array of 100 strings for **b** field, array of 100 doubles for **c** field. Instead of 100 groups of (?,?,?). Count is variable of cause, and depends on quantity of real data to insert/update (it would be nice to get batch updates too).

But I think, it depends on tarantools itself. Not only on this client. Is it possible at all?

**Comment by kyukhin** [comment]
No plans to support SQL batching in nearest future, sorry.

**Comment by Totktonada** [comment]
Or just define a function, which calls `box.execute()` in a loop. That's true, we usually don't provide built-in batch request support in language connectors.

**Comment by AndreyAlifanov** [comment]
I'm interested in SQL-queries, not in non-SQL features of Tarantool.
We have big platform which can connect to various SQL-sources. And we want to connect to Tarantool. Writing wrappers for translating SQL-queries to nonSQL and vice versa will be very hard task.

Calling execute in a loop is very unefficient way.
For example naive call of executes 1 mln times to insert records into space has about 109 seconds on my machine (it's fast, but not very impressive). Calls with grouping of 20 (?, ?, ?) with same count of records has only 10 seconds (in fact, it's 50 thousand calls of execute).
So, I think, if Tarantool could execute batch queries, it would be much faster.

**Comment by Totktonada** [comment]
There is one more ability: send requests asynchronously. I guess it is a bit tricky with this connector, but possible: the connector allows to [redefine](https://github.com/tarantool/tarantool-c/blob/917bfae96ce080e7ee72edf5d188764d78f2ca49/include/tarantool/tnt_stream.h#L44-L62) read and write functions.

If consistency matters, one should send all the requests within a [stream](https://www.tarantool.io/en/doc/latest/concepts/atomic/txn_mode_mvcc/#streams-and-interactive-transactions) within a transaction.
