### ISSUE TITLE
Lnik to https://github.com/tarantool/tarantool/tree/master/connector/c broken

### ISSUE THREAD

**Issue by timoc** [tarantool/tarantool-c#3]
The reccomended C driver link is broken.
https://github.com/tarantool/tarantool/tree/master/connector/c

**Comment by bigbes** [comment]
I'm sorry, but where do you find this link?

**Comment by timoc** [comment]
No idea. I'm sure it was relevant a year ago, does not seem so now.

**Comment by bigbes** [comment]
I'm sorry, Tim :) We created new version of tarantool-c for 1.6. If you're
still interested - you may use it.


2015-06-11 17:03 GMT+03:00 Tim <notifications@github.com>:

> No idea. I'm sure it was relevant a year ago, does not seem so now.
>
>
С наилучшими пожеланиями, Евгений.
