### ISSUE TITLE
Add array conversion specifiers to tnt_object_vformat

### ISSUE THREAD

**Issue by rtokarev** [tarantool/tarantool-c#31]
It would be great to add array conversion specifiers to tnt_object_vformat, that will allow to add few objects of the same type. I suggest following format: "%.*u", cnt, arr.

**Comment by bigbes** [comment]
Well, it's good idea, but there's a lot of questions:
1) What shall we do with string format specifier? "%.*s". It's already used in `tnt_object_vformat`
2) If you has varied sized arrays/maps, it's better to use 'tnt_object_add_*'
