### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by taroff** [tarantool/tarantool-c#37]
Добрый день! В вашем примере есть утечка памяти.
http://pastebin.com/xAKYkWPX
Методом перебора выяснилось что она связана с reply.
Т.е. в таком виде кол-во памяти расходуемой процессом не меняется:
http://pastebin.com/MyyrN4sM

**Comment by bigbes** [comment]
Спасибо, я обязательно взгляну.

With best regards, Eugene.

15 июня 2016 г., 13:05 пользователь taroff <notifications@github.com>
написал:
