### ISSUE TITLE
Add tarantool-c to Tarantool buildbot

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool-c#4]
+ Write RPM specs/DEB rules and push they to the repository. Please use package name that confirms official distributive naming conventions (e.g. tarantool-c-dev)
+ Add this project to build bot (http://build.tarantool.org/)
+ Check that module build and can be installed from tarantool.org repository

**Comment by kostja** [comment]
Is this done?

**Comment by Sulverus** [comment]
not yet. writed in todo for next scrum

**Comment by bigbes** [comment]
We, currently, don't have stable method for writing/testing/building
deb/rpm packages. Let's wait until we'll write c conenctor?

С наилучшими пожеланиями, Евгений.

2015-04-09 13:49 GMT+03:00 Andrew <notifications@github.com>:

**Comment by Sulverus** [comment]
@bigbes, testing/building - buildbot + docker tests? It's possible to add docker tests for connectors:
0. up container
1. install tarantool package
2. install connector package
3. do some script to test installed connector

**Comment by Sulverus** [comment]
ok. waiting for tarantool-c release from @bigbes

**Comment by bigbes** [comment]
Version released

**Comment by bigbes** [comment]
@Sulverus you can add it to buildbot

**Comment by Sulverus** [comment]
Found some truble with debian packaging with pbuilder
```
 .git/refs/remotes/origin/HEAD
dpkg-source: info: use the '3.0 (quilt)' format to have separate and documented changes to upstream files, see dpkg-source(1)
dpkg-source: unrepresentable changes to source
ERROR:root:Command failed with code 1 with errcode 1
ERROR:root:Aborting
```

**Comment by bigbes** [comment]
Where can i see full log of build?

С наилучшими пожеланиями, Евгений.

2015-06-16 11:29 GMT+03:00 Andrew <notifications@github.com>:

**Comment by Sulverus** [comment]
Done. 
1. Buildbot updated
2. RPM and DEB specs fixed with @bigbes 
3. Published libtarantool-c + dev + dbg + dsc for master repo
