### ISSUE TITLE
Type mismatch, counter overflow

### ISSUE THREAD

**Issue by cyanide-burnout** [tarantool/tarantool-c#44]
https://github.com/tarantool/tarantool-c/blob/master/tnt/tnt_request.c#L219

stream has uint64_t as a counter while function tnt_request_compile returns int64_t with use negative values to show error.

I guess boundary control is required:
```
s->reqid ++;
s->reqid &= INT64_MAX;
req->hdr.sync = s->reqid;
```

**Comment by cyanide-burnout** [comment]
https://github.com/tarantool/tarantool-c/blob/ae5d9b77b90100b752590f6c1dd4aa544f389930/tnt/tnt_request.c#L282
https://github.com/tarantool/tarantool-c/blob/ae5d9b77b90100b752590f6c1dd4aa544f389930/tnt/tnt_request.c#L319

**Comment by bigbes** [comment]
Well, you got me. That feature needs "some" refactoring.
