### ISSUE TITLE
Зависает клиент

### ISSUE THREAD

**Issue by cerevra** [tarantool/tarantool-c#47]
Привет
Есть несколько процедурок на стороне tarantool'а на С. Есть клиенты, написанные на tarantool-c
Когда делаю батчинг двух и более запросов, то через 5-10-20 секунд случается затык в области функции tnt_flush() - она просто не возвращает управление и повисает
Проблема воспроизводится просто: 1 клиент ходит сихронно в цикле. И неважно что за процедурка дергается: просто эхо, select или upsert c box_txn_begin()/box_txn_commit()
Кажется, так не должно быть

Логи, код:
https://gist.github.com/cerevra/922e90d9c978b81a066af45e20e6ee7a

**Comment by rtsisyk** [comment]
Caused by https://github.com/tarantool/tarantool/issues/946

**Comment by bigbes** [comment]
Вы пишете батч, а читаете один ответ.
