### ISSUE TITLE
Remote procedure call

### ISSUE THREAD

**Issue by anton19870803** [tarantool/tarantool-c#52]
Is it possible to call a remote procedure with a parameter?
In documentation https://tarantool.org/doc/book/connectors/index.html#id1 there is an example with remote procedure call without a parameter:

```c
   struct tnt_stream *tuple = tnt_object(NULL);       /* MAKE REQUEST */
   struct tnt_stream *arg; arg = tnt_object(NULL);
   tnt_object_add_array(arg, 0);
   struct tnt_request *req1 = tnt_request_call(NULL); /* CALL function f() */
   tnt_request_set_funcz(req1, "f");
   tnt_request_set_tuple(req1, arg);
   uint64_t sync1 = tnt_request_compile(tnt, req1);
   tnt_flush(tnt); 
```

Can you give me a tip how can I modify this code if function f has an argument.

**Comment by bigbes** [comment]
`tnt_request_set_tuple(req1, arg);` is an array of arguments.
Modifying this part:
```c
struct tnt_stream *arg; arg = tnt_object(NULL);
tnt_object_add_array(arg, 0);
```
you'll modify arguments of this request

**Comment by anton19870803** [comment]
Thanks, for reply. It works. I should have guessed it myself. Sorry for bothering.
