### ISSUE TITLE
Null pointer dereference in tnt_schema_free

### ISSUE THREAD

**Issue by yurikhan** [tarantool/tarantool-c#55]
To reproduce:

```c
struct tnt_stream * s = tnt_net(NULL);
tnt_stream_free(s);
```

Expected behavior: No effect.

Observed behavior: Segmentation fault.

What happens:

* In `tnt_net`, `s->data` is set to a newly allocated `tnt_stream_net` structure.
* `s->data` is filled with zero bytes. After that, select members of `s->data` are initialized.
* `s->free` is set to `tnt_net_free`.
* Several more members are initialized. Notably, `s->data->schema` is left zero-initialized.
* During destruction, `tnt_schema_free` is called with a null pointer argument.
* `tnt_schema_free` does not check its argument. It attempts to dereference the null pointer, theoretically invoking undefined behavior and in practice causing a segfault.

**Comment by bigbes** [comment]
Fixed! Thank you for your bug report.
