### ISSUE TITLE
Queues in C?

### ISSUE THREAD

**Issue by xpk** [tarantool/tarantool-c#67]
I understand the Tarantool C client does not support working with Tarantool Queue.
Are there plans to implement this functionality any soon? What are the possible workarounds at the moment?
I only really need to put data into a simple queue from C++ code. How hard can it be to add this to tarantool-c? Any tips / examples / points to related places in the client code are appreciated.
Thanks

**Comment by bigbes** [comment]
You should use `call`/`eval` to access queue functions. Example of this kind of library is: https://github.com/tarantool-php/queue/blob/master/src/Queue.php
